server:
  port: 8088
spring:
#  db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password:
    jpa:
      show_sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  #  end db

#  upload file max 10MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  upload file max 10MB

#variable global
api:
  prefix: api/v1
#variable global